Dinesh
csankit0108/Delmar pull request #11
Opened 2022-07-27 07:07 UTC by dineshdeverakonda

Created a trigger for sharing case and avoid duplicates.
Created an LWC component for customer Collaboration
Created two flows for changing case owner and send alerts and notifications to collaborators.
Created a custom object called Case Collaborator
Created a custom meta data in the trigger.

2022-07-27 08:45 UTC, csankit0108 commented
@dineshdeverakonda add try-catch blocks for all the methods and use the DEL_Utils class to create exception logs whenever an exception occurs. See DEL_EmailMessagesTriggerHelper for reference

2022-07-27 08:45 UTC, csankit0108 commented
add all the new component names which you have committed to the package.xml as well.

2022-07-27 08:46 UTC, csankit0108 requested changes

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationController.cls
> +* @ Purpose         :   To handle the trigger events for DEL_CaseCollaborationTrigger
updates the purpose, this doesn't look like its being used in the trigger.

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationController.cls
> +    public static List<User> getUserData(Id idCaseId, String strUserName){
```suggestion
    public static List<User> getUserData(Id idCaseId, String strUserName) {
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationController.cls
> +        List<User> list_User = [SELECT  AccountId, ContactId, Id, Name, Username,Email FROM User  WHERE Name LIKE : strpattern AND AccountId =: objCase.AccountId];
```suggestion
        List<User> list_Users = [SELECT 
                                              AccountId, 
                                              ContactId, 
                                              Id, 
                                              Name, 
                                              Username, 
                                              Email 
                                              FROM User 
                                              WHERE Name LIKE :strpattern AND 
                                              AccountId = :objCase.AccountId];
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationController.cls
> +    }
add new line before the start of a new method

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationController.cls
> +    public static void addContactCollaborator(List<Id> list_selectedUsers, Id idCaseId){
```suggestion
    public static void addContactCollaborator(List<Id> list_selectedUserIds, Id idCaseId) {
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationController.cls
> +        List< DEL_CaseCollaborator__c> list_objCaseCollaborator = new List< DEL_CaseCollaborator__c>();
```suggestion
        List<DEL_CaseCollaborator__c> list_CaseCollaborators = new List<DEL_CaseCollaborator__c>();
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationController.cls
> +            DEL_CaseCollaborator__c objCaseCollabRecord = new DEL_CaseCollaborator__c (
```suggestion
            DEL_CaseCollaborator__c objCaseCollaborator = new DEL_CaseCollaborator__c(
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationController.cls
> +      System.debug(list_objCaseCollaborator);
remove system.debug

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationController.cls
> +      insert list_objCaseCollaborator;
add IF condition to check if list_objCaseCollaborator is not empty before performing insert

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +{
align the opening braces( { ) as mentioned in the earlier comments

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +@TestSetup
Indentation is not correct for this method

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +    Account objAccount = new Account(
use DEL_TestUtility to create all the test data

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +    User objUser = [SELECT Id, Name , Profile.Name FROM User WHERE Profile.Name = 'CustomerPlus' ];
better to create a user with 'Customer Community Plus User' instead of querying for user. See DEL_CaseTriggerHelperTest in the CaseCommentsCmpChanges branch for reference

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +    * @ description : This method is used to test the 'getUserData' and 'addContactCollaborator'methods on DEL_CaseCollaborationTriggerHelper
it should be DEL_ContactCollaborationController, not DEL_CaseCollaborationTriggerHelper in the description

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +    private static void caseCollabTestMethod()
```suggestion
    private static void testCaseCollaboration() { 
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +        Case objCase = [SELECT Id, ContactId,AccountId FROM Case LIMIT 1];
```suggestion
        Case objCase = [SELECT Id, ContactId, AccountId FROM Case LIMIT 1];
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +        List<Id> list_userId = new List<Id>();
```suggestion
        List<Id> list_UserIds = new List<Id>();
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +        List<User> list_user = DEL_ContactCollaborationController.getUserData(objCase.Id,strName);
```suggestion
        List<User> list_Users = DEL_ContactCollaborationController.getUserData(objCase.Id, strName);
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +        for(User objUser : list_user){
```suggestion
        for (User objUser : list_user) {
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +        }
add new line here

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +        DEL_ContactCollaborationController.addContactCollaborator(list_userId,objCase.Id);
```suggestion
        DEL_ContactCollaborationController.addContactCollaborator(list_userId, objCase.Id);
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_ContactCollaborationControllerTest.cls
> +        Test.stopTest();
add assert statements to check if your getting the desired results

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/flows/DEL_CaseCollaborationFlow.flow-meta.xml
> +        <name>cn</name>
what is 'cn' ? make sure you're giving meaningful names for each action in the flow

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/flows/DEL_CaseCollaborationFlow.flow-meta.xml
> +                <stringValue>You have received an Collaboration Invite on this Case &quot;{!Get_Case.Subject}&quot;</stringValue>
you can use CaseNumber instead of Subject

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/flows/DEL_CaseCollaborationFlow.flow-meta.xml
> +                <stringValue>You have received an Collaboration Invite on this Case &quot; {!Get_Case.Subject} &quot;</stringValue>
use CaseNumber instead of Subject

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/flows/DEL_CaseCollaborationFlow.flow-meta.xml
> +        <name>assigninguser</name>
naming has to be like AssigningUser, Label- Assigning User and give a small description at every action in the flow what we are doing there

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/flows/DEL_CaseCollaborationFlow.flow-meta.xml
> +                <stringValue>collabnotification</stringValue>
Update the notification type name to 'DEL_CaseCollaborationNotification' and use it here.

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/flows/DEL_CaseCollaborationFlow.flow-meta.xml
> +        <text>&lt;pre class=&quot;ql-syntax&quot; spellcheck=&quot;false&quot;&gt;You have received an Collaboration Invite on this Case : {!Get_Case.Subject}
use CaseNumber instead of Subject

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/flows/DEL_ChangeCaseOwnerFlow.flow-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
We thought of not having this flow right? So you don't need to include this flow.

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.html
> +    <lightning-card title="Delmar Customer Search">
have the title as a design attribute without hardcoding it here

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.html
> +          <lightning-button label="Collaborate" variant="brand" onclick={collaborateContactHandler}></lightning-button>
```suggestion
          <lightning-button label=" Add Collaborator" variant="brand" onclick={collaborateContactHandler}></lightning-button>
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.js
> +import { api, LightningElement, track,wire } from 'lwc';
```suggestion
import { api, LightningElement, track, wire } from 'lwc';
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.js
> +    searchKey='';
```suggestion
    strSearchKey = '';
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.js
> +    @wire(getUserData, {idCaseId : '$recordId', strUserName : '$searchKey'})
have the idCaseId & strUserName parameters in separate lines. See handleOnClick() method in del_caseCollaborationComponent for reference

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.js
> +        for (let i = 0; i<selectedRecord.length; i++) {
try using the For/of loop instead of this

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.js
> +        }
add new line after this

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.js
> +            const event = new ShowToastEvent({
create a method for showing toast messages and call it from wherever needed. Similar to how its used in del_caseCollaborationComponent

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.js
> +    cols = [
```suggestion
    list_Columns = [
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.js
> +        {label:'Name', fieldName:'Name' , type:'text'},
```suggestion
        {label: 'Name', fieldName: 'Name', type: 'text'},
```

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/triggers/DEL_CaseCollaborationTrigger.trigger
> +trigger DEL_CaseCollaborationTrigger on DEL_CaseCollaborator__c (after insert, before insert,after delete)
remove after delete context, its not being used right now

2022-07-27 08:46 UTC, csankit0108 commented on Delmar/force-app/main/default/triggers/DEL_CaseCollaborationTrigger.trigger
> +    {
{ should start in the previous line

2022-07-27 11:51 UTC, dineshdeverakonda commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.js
> +    @track contacts;
you mean @track contacts?

2022-07-27 12:28 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_contactCollaborator/del_contactCollaborator.js
> +    @track contacts;
yes

2022-07-27 15:24 UTC, csankit0108 commented
Give a meaningful name to your pull requests. It should give an idea what functionality you are merging.

2022-07-27 15:27 UTC, dineshdeverakonda commented
Sure ankit.

On Wed, 27 Jul, 2022, 8:54 pm CS Ankit, ***@***.***> wrote:

> Give a meaningful name to your pull requests. It should give an idea what
> functionality you are merging.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/csankit0108/Delmar/pull/11#issuecomment-1196905357>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZWWHFTI46NBPP77YD7DHLTVWFIDXANCNFSM54YOTXLA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-27 17:25 UTC, dineshdeverakonda commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationTriggerHelperTest.cls
> +    User objUser = [SELECT Id FROM User WHERE Profile.Name = 'AgentProfile'];
This is Standard User profile ,I cloned it with that profile with custom objects permissions and named agentprofile.It works only with agents and their profile is agentprofile. thats why i tested with that profile.

2022-07-28 05:13 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationTriggerHelperTest.cls
> +    User objUser = [SELECT Id FROM User WHERE Profile.Name = 'AgentProfile'];
Yes, but this query might not return any record in other orgs so this test class will fail during deployment

2022-07-29 09:11 UTC, csankit0108 requested changes
1. I made some changes to lwc & apex controller, make sure to pull the changes from the branch and deploy to your org. Renamed the lwc to del_addCaseCollaboratorComponent so it would create a new cmp in your org. Use this cmp while testing.
2. I'm able to add collaborator without selecting any users and it shows success message. Add a validation to select at least one user. This is already done in del_caseCollaborationComponent.html. Refer that cmp.
3. "Add Collaborator" button in the lwc is displaying properly in community but in salesforce record page. Check the styling and make sure it displays properly everywhere.

2022-08-01 08:52 UTC, csankit0108 approved these changes

2022-08-01 08:52 UTC, merged