New changes case collaboration component
csankit0108/Delmar pull request #22
Opened 2022-08-05 12:28 UTC by vkkurre

1. Removed all Edit/Delete Option.
2. Added Custom Labels for Placeholder Text, Error Message and Success Message.

2022-08-05 14:34 UTC, csankit0108 requested changes

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +        @AuraEnabled public Map<Id, List<ContentVersion>> list_Attachments;
```suggestion
        @AuraEnabled public Map<Id, List<ContentVersion>> map_AttachmentsByCaseCommentId;
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +        Map<Id, List<ContentVersion>> map_ContentVersionByCaseCommentId = new Map<Id, List<ContentVersion>>();
```suggestion
        Map<Id, List<ContentVersion>> map_ContentVersionsByCaseCommentId = new Map<Id, List<ContentVersion>>();
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +        List<Id> list_caseCommentIds = new List<Id>();
```suggestion
        List<Id> list_CaseCommentIds = new List<Id>();
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +        List<Id> list_fileIds = new List<Id>();
remove this if not used anywhere

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +            if (objResponseWrapper.list_CaseComments.size() > 0) {
```suggestion
            if (!objResponseWrapper.list_CaseComments.ieEmpty()) {
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +                List<ContentDocumentLink> list_contentDocumentLinks = [SELECT
```suggestion
                List<ContentDocumentLink> list_ContentDocumentLinks = [SELECT 
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +                if (list_contentDocumentLinks.size() > 0) {
```suggestion
                if (!list_contentDocumentLinks.isEmpty()) {
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +                    List<ContentVersion> list_contentVersions = [SELECT
```suggestion
                    List<ContentVersion> list_ContentVersions = [SELECT 
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +                                                                IN : map_ContentDocumentLinkByContentDocumentId.KeySet()
```suggestion
                                                                IN :map_ContentDocumentLinkByContentDocumentId.KeySet()
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +                            map_ContentVersionByCaseCommentId.get(strCommentId).addAll(new List<ContentVersion> { objContentVersion } );
```suggestion
                            map_ContentVersionByCaseCommentId.get(strCommentId).add(objContentVersion);
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationController.cls
> +                }
add new line after this

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/labels/CustomLabels.labels-meta.xml
> +<CustomLabels xmlns="http://soap.sforce.com/2006/04/metadata">
update the custom label names as mentioned to you.

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_caseCollaborationComponent/del_caseCollaborationComponent.html
> +                                                                                    <lightning-icon icon-name="doctype:attachment" alternative-text="Download" title={objFile.Title}
you can "Download" also as a custom label

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_caseCollaborationComponent/del_caseCollaborationComponent.js
> +                let objAttachmentList = JSON.parse(JSON.stringify(data.list_Attachments));
```suggestion
                let list_Attachments = JSON.parse(JSON.stringify(data.list_Attachments));
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_caseCollaborationComponent/del_caseCollaborationComponent.js
> +                for (var commentIdKey in objAttachmentList) {
```suggestion
                for (var idCaseCommentId in objAttachmentList) {
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_caseCollaborationComponent/del_caseCollaborationComponent.js
> +                    let list_eachCommentAttachmentList = objAttachmentList[commentIdKey];
```suggestion
                    let list_AttachmentsTemp = objAttachmentList[commentIdKey];
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_caseCollaborationComponent/del_caseCollaborationComponent.js
> +                    for (let objAttachmentOfComment of list_eachCommentAttachmentList) {
```suggestion
                    for (let objAttachment of list_eachCommentAttachmentList) {
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_caseCollaborationComponent/del_caseCollaborationComponent.js
> +                        objAttachmentOfComment["strDownloadURL"] = DEL_FileDownloadURL+objAttachmentOfComment.ContentDocumentId;
```suggestion
                        objAttachmentOfComment["strDownloadURL"] = DEL_FileDownloadURL + objAttachmentOfComment.ContentDocumentId;
```

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_caseCollaborationComponent/del_caseCollaborationComponent.js
> +                for (var commentIdKey in objAttachmentList) {
have a comment mentioning what we are doing in this loop before staring the loop

2022-08-05 14:34 UTC, csankit0108 commented on Delmar/force-app/main/default/lwc/del_caseCollaborationComponent/del_caseCollaborationComponent.js
> +            //this.strBody = this.template.querySelector(".nullify").value;
remove this line instead of commenting

2022-08-05 17:54 UTC, vkkurre commented on Delmar/force-app/main/default/labels/CustomLabels.labels-meta.xml
> +<CustomLabels xmlns="http://soap.sforce.com/2006/04/metadata">
Okay Ankit.

2022-08-07 15:35 UTC, csankit0108 approved these changes

2022-08-07 15:35 UTC, merged