AddedChanges
csankit0108/Delmar pull request #37
Opened 2022-08-22 13:51 UTC by dineshdeverakonda

Created a URL field on Case Collaboration called Case Link and populate this field in the trigger based on if the User selected in the lookup is an Agent/Customer and use this field in the View Case button in the email template(This way we can avoid creating new template).
CHANGES
1) Changes in TriggerHelperClass and Trigger.
2)Made changes in Email Templates added view button on all collaboration email templates(english french spanish)
3)Created a custom field on CaseCollaborator called CaseLink__c

2022-08-22 14:24 UTC, csankit0108 requested changes
@dineshdeverakonda Include the Custom field as well(CaseLink__c)

2022-08-22 14:24 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationTriggerHelper.cls
> +        String strHTML = '';
remove this as it's not being used

2022-08-22 14:24 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationTriggerHelper.cls
> +        strSFURL = URL.getSalesforceBaseUrl().toExternalForm();
You can assign this in line 66 itself

2022-08-22 14:24 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationTriggerHelper.cls
> +        }
add new line

2022-08-22 14:24 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationTriggerHelper.cls
> +                objCaseCollaborator.CaseLink__c = strCommnunityURL + '/'+objCaseCollaborator.Case__c;
```suggestion
                objCaseCollaborator.CaseLink__c = strCommnunityURL + '/' + objCaseCollaborator.Case__c;
```

2022-08-22 14:24 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationTriggerHelper.cls
> +            }
```suggestion
            } else {
```

2022-08-22 14:24 UTC, csankit0108 commented on Delmar/force-app/main/default/classes/DEL_CaseCollaborationTriggerHelper.cls
> +                objCaseCollaborator.CaseLink__c = strSFURL + '/'+objCaseCollaborator.Case__c;
```suggestion
                objCaseCollaborator.CaseLink__c = strSFURL + '/' + objCaseCollaborator.Case__c;
```

2022-08-22 14:24 UTC, csankit0108 commented on Delmar/force-app/main/default/triggers/DEL_CaseCollaborationTrigger.trigger
> +         DEL_CaseCollaborationTriggerHelper.handleDuplicates(trigger.new);
Call the handleDuplicates() first

2022-08-22 14:48 UTC, pradeepchary commented
Rename Case Link__c as Case URL (CaseUrl__c)

2022-08-23 07:20 UTC, csankit0108 approved these changes

2022-08-23 07:21 UTC, merged